<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.4.3.2 setup script
 * Date: Mon, 16 Apr 2012 16:19:32 -0700
 */

/* Servers configuration */
$i = 0;

/* Server: vergil.u.washington.edu [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'vergil.u.washington.edu';
$cfg['Servers'][$i]['port'] = '46468';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'Purple&Gold1861';

/* End of servers configuration */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
